# Generated by Django 3.1.1 on 2021-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210206_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmarcy',
            name='title',
        ),
    ]
