# Generated by Django 3.1.1 on 2021-02-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pharmarcy_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pharmarcy',
            new_name='Pharmacy',
        ),
    ]
