# Generated by Django 3.1.6 on 2021-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210206_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
